
spring.application.name=MetodologiaEspiral

server.port=8081

spring.datasource.url=jdbc:postgresql://ep-orange-fire-a5x61c1z-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7QkE8uAFRUyG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=metodologiaespiralgrupo1@gmail.com
spring.mail.password=iqzxzxzdcpeeoknw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com




